### ISSUE TITLE
执行export_llama3.py时为什么会导出一大堆中间文件（参数）？

### ISSUE THREAD

**Issue by Lingzzyy** [luchangli03/export_llama_to_onnx#16]
生成了一大堆看起来像是参数的文件，其中生成的的llama3.onnx文件可以在netrons中可视化，但只有1600KB无法用于部署

**Comment by luchangli03** [comment]
使用onnx.load然后再重新onnx.save(onnx_model, model_path_out, save_as_external_data=True)

**Comment by Lingzzyy** [comment]
感谢作者回答！！
